%%{init: {'theme': 'dark'}}%%
flowchart TB
    S[ИС SkyNet<br/>Система обработки заявок]

    subgraph M1["Модуль авторизации"]
      M1a[Вход по логину и паролю]
      M1b[Восстановление пароля по email]
      M1c[Ограничение попыток входа]
    end

    subgraph M2["Модуль заявок"]
      M2a[Создание заявки]
      M2b[Редактирование заявки]
      M2c[Мягкое удаление]
      M2d[Смена статусов]
      M2e[Назначение исполнителя]
    end

    subgraph M3["Модуль поиска и фильтрации"]
      M3a[Поиск]
      M3b[Фильтры]
      M3c[Пагинация]
    end

    subgraph M4["Модуль уведомлений"]
      M4a[Уведомления в системе]
      M4b[Email при смене статуса]
      M4c[SMTP]
    end

    subgraph M5["Модуль пользователей"]
      M5a[Добавление пользователя]
      M5b[Блокировка/удаление пользователя]
      M5c[Смена пароля]
      M5d[Роли: Клиент/Оператор/Админ]
    end

    subgraph M6["Модуль базы знаний"]
      M6a[Добавление статей]
      M6b[Импорт TXT]
      M6c[Просмотр и поиск]
    end

    subgraph M7["Модуль отчетов"]
      M7a[Отчеты по операторам]
      M7b[Диаграммы]
      M7c[Экспорт CSV/XLSX]
    end

    S --> M1
    S --> M2
    S --> M3
    S --> M4
    S --> M5
    S --> M6
    S --> M7

    M1 --> M2
    M2 --> M3
    M2 --> M4
    M2 --> M7
    M5 --> M1
    M5 --> M2
    M6 --> M2
